### ISSUE TITLE
highchart with parameterized throw error

### ISSUE THREAD

**Issue by hakantekbasgit** [awesome-panel/panel-highcharts#14]
I'm receiving an error when I'm running in panel 0.13. Error message is "TypeError: Read-only parameter 'event' cannot be modified"

When I remove param.Parameterized, it works. @MarcSkovMadsen if you can help me to figure out whether I'm making a mistake or this is a bug, I will be very grateful.

```
import panel as pn
import param
import polars as pl
import panel_highcharts as ph

pl.Config.set_tbl_cols(12)
pl.Config.set_tbl_rows(20)

ph.config.theme("auto")
pn.extension('highchart',sizing_mode="stretch_width")

class dashboard(param.Parameterized):

    def __init__(self,**params):
        super().__init__(**params)

    def tag_chart(self):
        configuration = {
            "title": {"text": "HighChart Pane"},
            "series": [
                {
                    "name": "series1",
                    "data": [1, 2, 3, 4, 5],
                }
            ]
        }

        return pn.panel(ph.HighChart(object=configuration, sizing_mode="stretch_both", min_height=500))



    def create_layout(self):

        watch_event_layout = pn.Column(pn.Column(self.tag_chart))


        return watch_event_layout

dashboard_object = dashboard().create_layout()
dashboard_object.servable(title='Technical Intelligence Dashboard - Privacy Chains')```

**Comment by MarcSkovMadsen** [comment]
Hi @hakantekbasgit 

I also just identified this issue. I've tried both with Panel 0.13.1 and Panel 0.14.0. But they both show this error. I've also just released a new version of `panel-highcharts` which still has this error.

I've investigated and cannot find the cause. I notice that if I move the mouse slowly there is no issue. But if I hover fast then I see the issue.

I will report the below minimum reproducible example on the Panel github too. Maybe it is an issue with Panel?

```python
import json

import requests

import panel_highcharts as ph

ph.config.theme("auto")

import panel as pn

pn.extension("highstock")

data = requests.get(
    "https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/new-intraday.json"
).json()
configuration = {
    "title": {"text": "AAPL stock price by minute"},
    "series": [
        {
            "name": "AAPL",
            "type": "candlestick",
            "data": data,
            "tooltip": {"valueDecimals": 2},
            "allowPointSelect": "true",
            "point": {
                "events": {
                    "mouseOver": "@mouseOverFun",
                }
            },
        }
    ],
}
plot_pane = ph.HighStock(object=configuration, sizing_mode="stretch_both", min_height=600)
pn.Column(plot_pane, plot_pane.param.event).servable()
```

https://user-images.githubusercontent.com/42288570/195974128-9956874f-3197-46d4-bfd6-2251bae54de5.mp4

**Comment by MarcSkovMadsen** [comment]
I've released `panel-highcharts==20221015.4` which should fix the issue. If it does not please let me know and reopen this issue.

Thanks for using `panel-highcharts` and reporting the issue. If you can share anything about your use case I would like to learn. I would also love if you wanted to connect on [Twitter](https://twitter.com/MarcSkovMadsen) or [LinkedIn](https://www.linkedin.com/in/marcskovmadsen)

**Comment by hakantekbasgit** [comment]
It is really fast. incredible. I have two applications. Both of them were not running in previous versions. one is simple one. I tried it. Now it is working. If I experience same problem on complex one, I will write. But Thanks for your fast actions. You're really contributing a lot. 

I hope panel's memory problem will be solved in next versions and I will use it more. but in one of your posts in disclosure, you mentioned you're not experiencing any memory leak, maybe you can add a special section to explain what your design approach, what you're recommending when build a complex panel applications? Thanks again.

**Comment by MarcSkovMadsen** [comment]
Have you reported the memory problems on the Panel Github. Otherwise please do. Its the only way we get it solved.
