### ISSUE TITLE
blank graph when running in jupyter

### ISSUE THREAD

**Issue by lovepocky** [awesome-panel/panel-highcharts#9]
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/10250869/161025299-d5e6028d-2c83-440b-83f6-72eeae039829.png">

**Comment by MarcSkovMadsen** [comment]
Thanks for reporting.

**Comment by MarcSkovMadsen** [comment]
I just tried reproducing with panel==0.14.0 and panel-highcharts==20221015.4, and I cannot.

![image](https://user-images.githubusercontent.com/42288570/195975624-ca9ae936-2158-4c45-8bc5-0b2df63aa1bd.png)

Feel free to reopen if you still have the issue
